name: Start Shadowsocks & playit Tunnel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: تثبيت Shadowsocks
      run: |
        sudo apt update
        sudo apt install -y shadowsocks-libev

    - name: إعداد ملف Shadowsocks
      run: |
        cat > config.json <<EOF
        {
          "server":"0.0.0.0",
          "server_port":1080,
          "password":"mypassword123",
          "timeout":300,
          "method":"aes-256-gcm"
        }
        EOF

    - name: تشغيل Shadowsocks
      run: |
        nohup ss-server -c config.json > ss.log 2>&1 &
        sleep 3
        echo "[✓] Shadowsocks is running"
        tail -n 10 ss.log || true

    - name: تحميل وتشغيل playit.gg
      env:
        PL: ${{ secrets.PL }}
      run: |
        wget -qO playit.tar.gz https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64.tar.gz
        tar -xzf playit.tar.gz
        chmod +x playit

        echo "[✓] Authenticating with token..."
        ./playit auth --token "$PL" || (echo "[×] Auth failed"; exit 1)

        echo "[✓] Starting playit tunnel..."
        nohup ./playit > playit.log 2>&1 &
        sleep 5
        tail -n 10 playit.log || true
